config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("nft_cryptopunks_generator.users.urls", namespace="users")),
    path("", include("nft_cryptopunks_generator.avatar.urls", namespace="collectibles")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

nft_cryptopunks_generator/avatar/urls.py
from django.urls import include, path
from .views import TemplateList, collectableDetail, createNft, delete_image, update_settings, savearr, delete_section, upload_image, Generatelist, generate_list, generate_nft, update_image, reset_image, delete_image, delete_partarr
app_name = "collectibles"
urlpatterns = [
    path("", TemplateList.as_view(), name="home"),
    path("create/", createNft, name="collectables_create"),
    path("<int:pk>/", collectableDetail.as_view(), name="collectables_detail"),
    path("section/<int:pk>/", update_settings, name="update_settings"),
    path("section/delete/<int:pk>/", delete_section, name="delete_section"),
    path("section/image/<int:pk>/", upload_image, name="upload_image"),
    path("generate/<int:pk>/", generate_nft, name="generate_nft"),
    path("delete/imge/<int:pk>/", delete_image, name="delete_image"),
    path("update/imge/<int:pk>/", update_image, name="update_image"),
    path("reset/imge/<int:pk>/", reset_image, name="reset_image"),
    path("<int:id>/section/", TemplateList.as_view(), name="template_list"),
    path("<int:pk>/save_arr/", savearr, name="save_arr"),
    path("<int:pk>/generate_part/", generate_list, name="generate_part"),
    path("delete/<int:pk>/", delete_partarr, name="delete_partarr"),
]

nft_cryptopunks_generator/users/urls.py
from django.urls import path

from nft_cryptopunks_generator.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

nft_cryptopunks_generator/avatar/models.py
from operator import truediv
from django.db import models
# Create your models here.
from django.db.models import F
from django.db.models.aggregates import Max
from django_validated_jsonfield import ValidatedJSONField as JSONField
from django.conf import settings
from django.urls import reverse

class NftTemplate(models.Model):
    title = models.CharField(max_length=225,blank=True, null=True)
    file = models.ImageField(blank=True, null=True,max_length=500)
    variants = models.IntegerField(blank=True, null=True)
    variants_used = models.IntegerField(blank=True, null=True)
    width = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("collectibles:collectables_detail", kwargs={"pk": self.pk})
    def get_nft_generate(self):
        return Arrpart.objects.filter(nft_template__id=self.id).count()

class Arrpart(models.Model):
    nft_template = models.ForeignKey(NftTemplate, on_delete=models.CASCADE)
    arr = models.CharField(max_length=50000,unique=True)

class Sections(models.Model):
    nft_template = models.ForeignKey(NftTemplate, on_delete=models.CASCADE)
    name = models.CharField(max_length=225)
    position_x = models.FloatField()
    position_y = models.FloatField()
    sort_order = models.IntegerField(default=0,)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ('sort_order',)

    def get_absolute_url(self):
        return reverse("collectibles:collectables_detail", kwargs={"pk": self.nft_template.pk})
    

class Images(models.Model):
    image = models.ImageField()
    section = models.ForeignKey("Sections", on_delete=models.CASCADE)
    position_x = models.FloatField(null=True,blank=True)
    position_y = models.FloatField(null=True,blank=True)
    raretiy = models.IntegerField(default=0)
    width= models.FloatField(blank=True,null=True)
    height = models.FloatField(blank=True,null=True)
    sort_order = models.IntegerField(default=0,null=True,blank=True)
    exclude = models.ManyToManyField(
        "self", related_name="children"
    )    
    def __str__(self):
        return self.image.name
    
    class Meta:
        ordering = ('sort_order',)

class GeneratedArray(models.Model):
    _data_schema = {
        "type": "object",
        "properties": {
            "rarity": {
                "description": "generated set array",
                "type": "array",
                "items": {
                    "type": "string"
                },
            },
            "generatedSetArray": {
                "description": "generated set array",
                "type": "array",
                "items": {
                    "type": "string"
                },
            }
        },
        "default": {},  # note the top level default
        "additionalProperties": False,
    }
    data = JSONField(schema=_data_schema, editable=True)

nft_cryptopunks_generator/avatar/views.py
import re
from django.contrib import messages
from django.db.models import fields
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.postgres.aggregates import ArrayAgg
import operator
from django.db.models import Q
from functools import reduce
import base64
from django.core.files.base import ContentFile

# Create your views here.
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, ListView, CreateView,UpdateView
from django.views.generic.detail import DetailView
from django.views.decorators.csrf import csrf_exempt
import json
from django.core.serializers.json import DjangoJSONEncoder
from .models import NftTemplate, Sections, Images, Arrpart
from . import forms
from django.urls import reverse
from rest_framework import serializers
from . import models
from django.core import serializers as myser
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class ImageSerializer(serializers.ModelSerializer):
    class Meta:
        model = Images
        fields = ("exclude","image","sort_order","position_x","position_y")


class TemplateList(ListView):
    template_name = "avatar_generator/index.html"
    model = NftTemplate
    paginate_by = 100
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

@csrf_exempt
def savearr(request,pk):
    nft_template = get_object_or_404(NftTemplate,pk=pk)
    post_data =  request.POST
    print(post_data.get("data"))
    print("######################")
    if post_data:
        Arrpart.objects.create(arr=post_data.get("data"), nft_template=nft_template)
    return JsonResponse({"data": "uploaded"},status=200)

class Generatelist(ListView):
    model = Arrpart
    template_name = "avatar_generator/get.html"
    paginate_by = 1

    def get_queryset(self):
        print(self.kwargs.get("kwargs",None))
        qs = super().get_queryset()
        return qs

def generate_list(request,pk):
    query = request.GET.getlist('query',None)
    print(query)
    if query:
        query2 = reduce(operator.and_, (Q(arr__icontains = item) for item in query))
        user_list = Arrpart.objects.filter(query2,nft_template__pk=pk)
    else:
        user_list = Arrpart.objects.filter(nft_template__pk=pk)
    page = request.GET.get('page', 1)
    paginator = Paginator(user_list, 50)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    uscount = user_list.count()
    return render(request,"avatar_generator/get.html", { 'object_list': users,"count":uscount })

class collectableCreateView(CreateView):
    model = NftTemplate
    template_name = "avatar_generator/form.html"
    form_class = forms.NftTemplateFrom
    
def createNft(request):
    if request.method == "POST":
        form = forms.NftTemplateFrom(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save()
            return JsonResponse({"data":obj.id},status=200)
        else:
            print(form.errors)
            return JsonResponse({"data":str(form.errors)},status=200)
    else:
        return render(request, "avatar_generator/form.html", {"form":forms.NftTemplateFrom})
    
class collectableDetail(CreateView):
    model = Sections
    template_name = "avatar_generator/upload_sections.html"
    form_class = forms.SectionsFrom

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        context["object"] = NftTemplate.objects.get(id=pk)
        context["object_list"] = Sections.objects.filter(nft_template__id=pk)
        return context
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        pk = self.kwargs.get("pk")
        obj.nft_template =  NftTemplate.objects.get(id=pk)
        obj.save()
        return super().form_valid(form)


def update_settings(request,pk):
    obj = get_object_or_404(NftTemplate, pk=pk)
    form = forms.NftTemplateFrom(
        request.POST or None, request.FILES or None, instance=obj
    )
    if request.method == "POST":
        if form.is_valid():
            obj = form.save()
            msg = pgettext_lazy("Dashboard message", "Settings has been update  %s") % (
                obj.title,
            )
            messages.success(request, msg)
            return redirect( reverse("collectibles:collectables_detail", kwargs={"pk": pk}))
        else:
            msg = pgettext_lazy("Dashboard message", " %s") % (
                form.errors,
            )
            messages.success(request, msg)
            return redirect( reverse("collectibles:collectables_detail", kwargs={"pk":pk}))
    ctx = {"form": form, "form_url": reverse("collectibles:update_settings", kwargs={"pk":pk})}
    return TemplateResponse(request, "avatar_generator/form_modal.html", ctx)

def delete_section(request,pk):
    obj = get_object_or_404(Sections, pk=pk)
    nft_pk = obj.nft_template.pk
    if request.method == "POST":
        obj.delete()
        return redirect( reverse("collectibles:collectables_detail", kwargs={"pk":nft_pk}))
    ctx = {"form_url": reverse("collectibles:delete_section", kwargs={"pk":pk}), "object":obj}
    return TemplateResponse(request, "avatar_generator/delete_section.html", ctx)

def upload_image(request,pk):
    section = get_object_or_404(Sections, pk=pk)
    form = forms.ImageFrom(
        request.POST or None, request.FILES or None
    )
    if request.method == "POST":
        if form.is_valid():
            obj = form.save(commit=False)
            obj.section = section
            obj.position_x = section.position_x
            obj.position_y = section.position_y
            obj.sort_order = section.sort_order
            obj.save()
            msg = pgettext_lazy("Dashboard message", "Image Has Benn Uploaded ")
            messages.success(request, msg)
            return JsonResponse({"data":reverse("collectibles:collectables_detail", kwargs={"pk":section.nft_template.pk})},status=200)
        else:
            msg = pgettext_lazy("Dashboard message", " %s") % (
                form.errors,
            )
            messages.success(request, msg)
            return redirect( reverse("collectibles:collectables_detail", kwargs={"pk":pk}))
    ctx = {"form": form, "form_url": reverse("collectibles:upload_image", kwargs={"pk":pk}), "object":section}
    return TemplateResponse(request, "avatar_generator/images/detail_list.html", ctx)

def generate_nft(request, pk):
    nft = get_object_or_404(NftTemplate, pk=pk)
    sections = Sections.objects.filter(nft_template_id=pk)
    arr = []
    for section in sections:
        image_list = list(section.images_set.all().annotate(exluded=ArrayAgg('exclude')).values("id","image","position_x","position_y","exluded").distinct())
        serialized_q = json.dumps(list(image_list), cls=DjangoJSONEncoder)
        arr.append(serialized_q)
    return TemplateResponse(request, "avatar_generator/generate.html", {"sections":arr,"pk":pk,})

def delete_image(request,pk):
    image = get_object_or_404(Images,pk=pk)
    section = image.section.id
    if request.method == "POST":
        image.delete()
        msg = pgettext_lazy("Dashboard message", "Image Has Benn Deleted ")
        messages.success(request, msg)
        return redirect( reverse("collectibles:upload_image", kwargs={"pk":section}))
    ctx = { "form_url": reverse("collectibles:delete_image", kwargs={"pk":pk}), "object":image}
    return TemplateResponse(request, "avatar_generator/images/delete_image.html", ctx)


def update_image(request,pk):
    image = get_object_or_404(Images,pk=pk)
    section = image.section
    sections_selected = Sections.objects.filter(nft_template=section.nft_template).exclude(id=section.id).values_list("id", flat=True)
    images = Images.objects.filter(section_id__in=list(sections_selected))
    form = forms.ImageFromUpdate(data=request.POST or None,files=request.FILES or None,images_qs=images, instance=image)
    print(form.errors)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            msg = pgettext_lazy("Dashboard message", "Image Has Benn updated ")
            messages.success(request, msg)
        else:
            msg = pgettext_lazy("Dashboard message", str(form.errors))
            messages.success(request, msg)
        return redirect( reverse("collectibles:upload_image", kwargs={"pk":image.section.id}))
    ctx = { "form_url": reverse("collectibles:update_image", kwargs={"pk":pk}), "form": form,"object":image}
    return TemplateResponse(request, "avatar_generator/images/update_images.html", ctx)

def reset_image(request,pk):
    section = get_object_or_404(Sections, pk=pk)
    imgs = Images.objects.filter(section_id=pk)
    print(imgs)
    for img in imgs:
        img.exclude.clear()
        img.save()
    return redirect( reverse("collectibles:upload_image", kwargs={"pk":pk}))

@require_POST
def ajax_upload_image(request, obj_pk):
    section = get_object_or_404(Sections, pk=obj_pk)
    form = forms.ImageFrom(
        request.POST or None, request.FILES or None, section=section
    )
    ctx = {}
    status = 200
    if form.is_valid():
        image = form.save()
        ctx = {"id": image.pk, "image": None, "order": image.sort_order}
    elif form.errors:
        status = 400
        ctx = {"error": form.errors}
    return JsonResponse(ctx, status=status)


def product_image_delete(request, obj_pk, img_pk):
    section = get_object_or_404(Sections, pk=obj_pk)
    image = get_object_or_404(Images, pk=img_pk)
    if request.method == "POST":
        image.delete()
        msg = pgettext_lazy("Dashboard message", "Removed image %s") % (

nft_cryptopunks_generator/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

nft_cryptopunks_generator/templates/avatar_generator/delete_section.html
{% extends "modal_base.html" %}
{% load widget_tweaks %}
{% block action_url %}
{{ form_url }}
{% endblock %}
 
 {% block title %}
   Categorie
 {% endblock title %}
   
{% block content %}
<div class="row">
  <div class="col-lg-12">
        <p>Are you sure you want to delete <b>{{ object.name }}</b></p>
  </div><!--end col-->
</div>
    
    
{% endblock %}
{% block script %}

{% endblock %}

nft_cryptopunks_generator/templates/avatar_generator/form_modal.html
{% extends "modal_base.html" %}
{% load widget_tweaks %}
{% block action_url %}
{{ form_url }}
{% endblock %}
 
 {% block title %}
   Section
 {% endblock title %}
   
{% block content %}
<div class="form-group">
  <label for="nom" class="">Modifier les parameter de votre template</label>
      {% render_field form.title   class="form-control"%}
</div>
  <div class="form-group">
    <label for="nom" class="col-sm-12  col-form-label-sm">Width</label>
        {% render_field form.width   class="form-control"%}
</div>
<div class="form-group">
      <label for="nom" class="col-sm-12  col-form-label-sm">Height</label>
          {% render_field form.height   class="form-control"%}
</div>
    
{% endblock %}
{% block script %}

{% endblock %}

nft_cryptopunks_generator/templates/avatar_generator/generate.html
{% extends "base.html" %}
{% load static i18n %}
{% block content %}
    <div class="text-center mb-5">
     <div id="mydiv">
     </div>
      <div class="clear"></div>
      <button id="download" class="btn btn-success d-inline-block">Download all images</button>
    </div>
    <div>{{ sections }}</div>
    {% for section in sections %}
        myarr.push({{section|safe}})
    {% endfor %}
  
      
        
{% endblock %}
{% block inline_javascript %}
  <script src="https://unpkg.com/merge-images"></script>

  <script>
    function onlyUnique(value, index, self) {
      return self.indexOf(value) === index;
    }

    let myarr = []  
    {% for section in sections %}
        myarr.push({{section|safe}})
    {% endfor %}
    console.log({{section|safe}})
    let robots = myarr;
    let counter = 0;
    let newArr = robots[0]
    let reservArr = []
    let csutomArr = []
    while (counter < robots.length-1){
      for (let i = 0; i < newArr.length; i++) {
        for (let j = 0; j < robots[counter+1].length; j++) {
          if(Array.isArray(newArr[i])){
            csutomArr = [...newArr[i]] ;
            csutomArr.push(robots[counter+1][j])
            reservArr.push(csutomArr)
          }else{
            reservArr.push( [newArr[i],robots[counter+1][j]])
          }
        }
      }
      newArr = reservArr;
      reservArr = [];
      counter++;
    }
    function sort_by_key(array, key){
        return array.sort(function(a, b){
          var x = a[key]; var y = b[key];
          return ((x < y) ? -1 : ((x > y) ? 1 : 0));
        });
    }
    let treated_arry = []
    let unfound = []
    let i = 0;
    for (i = 0; i < newArr.length; i++) {
      let mergeArr = [];
      let excluded_all = [];
      let id_all = [];
      for (let j = 0; j < newArr[i].length; j++) {
        let tempElem = newArr[i][j];
        id_all.push(tempElem.id);
        excluded_all.push(tempElem.id);
        // excluded_all.push(...tempElem.exluded);
      }
      for (let j = 0; j < newArr[i].length; j++) {
        let tempElem = newArr[i][j];
        id_all.push(tempElem.id);
        excluded_all.push(...tempElem.exluded);
      }
      var unique = excluded_all.filter(onlyUnique);
      const filteredArray = unique.filter(value => id_all.includes(value))
      if (filteredArray.length >= newArr[i].length){
        for (let j = 0; j < newArr[i].length; j++) {
          let tempElem = newArr[i][j];
          mergeArr.push({src : "/media/"+tempElem.image, position_x: tempElem.position_x , position_y: tempElem.position_y, sort_order: tempElem.sort_order});
        } 
        
      }else{
        
      }
      if(mergeArr.length > 0){
        let sorted_arr = sort_by_key(mergeArr, 'sort_roder');
        treated_arry.push(sorted_arr);
      }
      //mergeImages(mergeArr,{width: 2000, height: 2000,quality:1}).then(b64 => imgElam.attr("src",b64))
    }

    let temporary = [];
    var j, chunk = 50;
    console.log(treated_arry.length)
    for (i = 0,j = treated_arry.length; i < j; i ++) {
      $.ajax({
        method: "post",
        dataType:     'json',
        url:          "{% url 'collectibles:save_arr' pk=pk %}",
        data:         {"data":JSON.stringify(treated_arry[i])},
      })
    }
    $("#download").click(function(){
      DownalodImage()
    })
    function DownalodImage(){
      console.log("dow")
      var images = document.getElementsByTagName('img');
      var srcList = [];
      var i = 0;
      if(images.length > i){
              srcList.push(images[i].src);
              var link = document.createElement("a");
              link.id=i;
              link.download = images[i].src;
              link.href = images[i].src;
              link.click();
              i++;
          }
      
    }
  </script>
{% endblock inline_javascript %}

nft_cryptopunks_generator/templates/avatar_generator/index.html
{% extends "base.html" %}
{% load widget_tweaks %}
  
{% block content %}
  <div class="row">
    {% for object in object_list %}
        <div class="col-md-4 mb-3">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{ object.file.url }}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{ object.title }}</h5>
          <p class="card-text">generated :{{ object.get_nft_generate }}</p>
          <a href="{% url "collectibles:collectables_detail" pk=object.pk %}" class="btn btn-primary">Details</a>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
{% endblock %}

{% block modal %}
  <!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Collectibles Settings</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url "collectibles:collectables_create" %}" method="post" >
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1">{{ form.title.label }}</label>
            {% render_field form.title class="form-control" %}
          </div>
          <div class="row">
            <div class="form-group col">
              <label for="exampleInputEmail1">{{ form.height.label }}</label>
              {% render_field form.height class="form-control" %}
            </div>
            <div class="form-group col">
              <label for="exampleInputEmail1">{{ form.width.label }}</label>
              {% render_field form.width class="form-control" %}
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div>
        </form>
      </div>
      
    </div>
  </div>
</div>
{% endblock modal %}
  

nft_cryptopunks_generator/templates/avatar_generator/upload_sections.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% block stylesheet %}
    <style>
       #collectable-template{
            cursor: crosshair;
        }
        .indicator{
            width: 5px;
            height: 5px;
            border-radius: 50%;
            background: red;
            position: absolute;
        }
        #image-container{
            position: relative;
            display: inline-block;
        }        
    </style>
{% endblock stylesheet %}
    
    {% block menu %}
    <a type="button" href="{% url "collectibles:update_settings" pk=object.pk %}" data-toggle="modal"  data-bs-toggle="modal" data-bs-target="#exampleModal" class="modal-trigger-custom btn  modal-trigger-custom" >
      Edit Settings
  </a> 
  <div class="m-3"> 
    <a type="button" href="{% url "collectibles:generate_part" pk=object.pk %}">
      Result
    </a>
  </div>
  <div class="m-3">
    <a type="button" href="{% url "collectibles:generate_nft" pk=object.pk %}">
      generate collection
    </a>
  </div>
  <div class="m-3">
    <a type="button" href="{% url "collectibles:delete_partarr" pk=object.pk %}">
      delete collection generated
    </a>
  </div>
  
    {% endblock menu %}
        
{% block content %}
    <h1>{{ object.title }}</h1>
    <div class="sections">
      {% for object in object_list %}
            <a  href="{% url "collectibles:upload_image" pk=object.pk %}"  >
              {{ object.name}}
            </a>
      {% endfor %}
    </div>
    <div id="image-container">
        <img id="collectable-template" width="{{ object.width }}" height="{{ object.height }}" src="{{ object.file.url }}" alt="">
        {% for object in object_list %}
            <div  href="{% url "collectibles:delete_section" pk=object.pk %}" data-toggle="modal"  data-bs-toggle="modal" data-bs-target="#exampleModal" class="modal-trigger-custom indicator" style="left:{{ object.position_x }}px; top: {{ object.position_y}}px"></div>
        {% endfor %}
    </div>

{% endblock content %}


{% block modal %}
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Add Section</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form action="." method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                      <div class="form-group">
                        <label for="exampleInputEmail1">{{ form.name.label }}</label>
                        {% render_field form.name class="form-control" %}
                      </div>
                      <div class="row">
                        <div class="form-group col">
                          <label for="exampleInputEmail1">{{ form.position_x.label }}</label>
                          {% render_field form.position_x class="form-control" %}
                        </div>
                        <div class="form-group col">
                          <label for="exampleInputEmail1">{{ form.position_y.label }}</label>
                          {% render_field form.position_y class="form-control" %}
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">{{ form.sort_order.label }}</label>
                        {% render_field form.sort_order class="form-control" %}
                      </div>
                    </div>
                  </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
        
      </div>
    </div>
  </div>
  {% include "modal.html" with id_modal="exampleModal" %}

{% endblock modal %}
    {% block inline_javascript %}
        <script>
            let x = 0;
            let y = 0;
            $("#collectable-template").on('click', function( e ) {
                let $this = $(this);
                var rect = e.target.getBoundingClientRect();
                x = e.clientX - rect.left; //x position within the element.
                y = e.clientY - rect.top;
                $("#id_position_x").val(x);
                $("#id_position_y").val(y);
                $('#exampleModalCenter').modal('show')
                $("#image-container").append("<div style='top:"+y+"px;left:"+x+"px' class='indicator'></div>")
            })
            $('#exampleModalCenter').on('hidden.bs.modal', function (e) {
                $("body").find(".indicator").last().remove();
            })
        </script>  
    {% endblock inline_javascript %}
        