config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("nft_cryptopunks_generator.users.urls", namespace="users")),
    path("", include("nft_cryptopunks_generator.avatar.urls", namespace="collectibles")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

nft_cryptopunks_generator/avatar/urls.py
from django.urls import include, path
from .views import TemplateList, collectableDetail, createNft, delete_image, update_settings, savearr, delete_section, upload_image, Generatelist, generate_list, generate_nft, update_image, reset_image, delete_image, delete_partarr
app_name = "collectibles"
urlpatterns = [
    path("", TemplateList.as_view(), name="home"),
    path("create/", createNft, name="collectables_create"),
    path("<int:pk>/", collectableDetail.as_view(), name="collectables_detail"),
    path("section/<int:pk>/", update_settings, name="update_settings"),
    path("section/delete/<int:pk>/", delete_section, name="delete_section"),
    path("section/image/<int:pk>/", upload_image, name="upload_image"),
    path("generate/<int:pk>/", generate_nft, name="generate_nft"),
    path("delete/imge/<int:pk>/", delete_image, name="delete_image"),
    path("update/imge/<int:pk>/", update_image, name="update_image"),
    path("reset/imge/<int:pk>/", reset_image, name="reset_image"),
    path("<int:id>/section/", TemplateList.as_view(), name="template_list"),
    path("<int:pk>/save_arr/", savearr, name="save_arr"),
    path("<int:pk>/generate_part/", generate_list, name="generate_part"),
    path("delete/<int:pk>/", delete_partarr, name="delete_partarr"),
]

nft_cryptopunks_generator/users/urls.py
from django.urls import path

from nft_cryptopunks_generator.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

nft_cryptopunks_generator/avatar/models.py
from operator import truediv
from django.db import models
# Create your models here.
from django.db.models import F
from django.db.models.aggregates import Max
from django_validated_jsonfield import ValidatedJSONField as JSONField
from django.conf import settings
from django.urls import reverse

class NftTemplate(models.Model):
    title = models.CharField(max_length=225,blank=True, null=True)
    file = models.ImageField(blank=True, null=True,max_length=500)
    variants = models.IntegerField(blank=True, null=True)
    variants_used = models.IntegerField(blank=True, null=True)
    width = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("collectibles:collectables_detail", kwargs={"pk": self.pk})
    def get_nft_generate(self):
        return Arrpart.objects.filter(nft_template__id=self.id).count()

class Arrpart(models.Model):
    nft_template = models.ForeignKey(NftTemplate, on_delete=models.CASCADE)
    arr = models.CharField(max_length=50000,unique=True)

class Sections(models.Model):
    nft_template = models.ForeignKey(NftTemplate, on_delete=models.CASCADE)
    name = models.CharField(max_length=225)
    position_x = models.FloatField()
    position_y = models.FloatField()
    sort_order = models.IntegerField(default=0,)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ('sort_order',)

    def get_absolute_url(self):
        return reverse("collectibles:collectables_detail", kwargs={"pk": self.nft_template.pk})
    

class Images(models.Model):
    image = models.ImageField()
    section = models.ForeignKey("Sections", on_delete=models.CASCADE)
    position_x = models.FloatField(null=True,blank=True)
    position_y = models.FloatField(null=True,blank=True)
    raretiy = models.IntegerField(default=0)
    width= models.FloatField(blank=True,null=True)
    height = models.FloatField(blank=True,null=True)
    sort_order = models.IntegerField(default=0,null=True,blank=True)
    exclude = models.ManyToManyField(
        "self", related_name="children"
    )    
    def __str__(self):
        return self.image.name
    
    class Meta:
        ordering = ('sort_order',)

class GeneratedArray(models.Model):
    _data_schema = {
        "type": "object",
        "properties": {
            "rarity": {
                "description": "generated set array",
                "type": "array",
                "items": {
                    "type": "string"
                },
            },
            "generatedSetArray": {
                "description": "generated set array",
                "type": "array",
                "items": {
                    "type": "string"
                },
            }
        },
        "default": {},  # note the top level default
        "additionalProperties": False,
    }
    data = JSONField(schema=_data_schema, editable=True)

nft_cryptopunks_generator/avatar/views.py
import re
from django.contrib import messages
from django.db.models import fields
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.postgres.aggregates import ArrayAgg
import operator
from django.db.models import Q
from functools import reduce
import base64
from django.core.files.base import ContentFile

# Create your views here.
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, ListView, CreateView,UpdateView
from django.views.generic.detail import DetailView
from django.views.decorators.csrf import csrf_exempt
import json
from django.core.serializers.json import DjangoJSONEncoder
from .models import NftTemplate, Sections, Images, Arrpart
from . import forms
from django.urls import reverse
from rest_framework import serializers
from . import models
from django.core import serializers as myser
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class ImageSerializer(serializers.ModelSerializer):
    class Meta:
        model = Images
        fields = ("exclude","image","sort_order","position_x","position_y")


class TemplateList(ListView):
    template_name = "avatar_generator/index.html"
    model = NftTemplate
    paginate_by = 100
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

@csrf_exempt
def savearr(request,pk):
    nft_template = get_object_or_404(NftTemplate,pk=pk)
    post_data =  request.POST
    print(post_data.get("data"))
    print("######################")
    if post_data:
        Arrpart.objects.create(arr=post_data.get("data"), nft_template=nft_template)
    return JsonResponse({"data": "uploaded"},status=200)

class Generatelist(ListView):
    model = Arrpart
    template_name = "avatar_generator/get.html"
    paginate_by = 1

    def get_queryset(self):
        print(self.kwargs.get("kwargs",None))
        qs = super().get_queryset()
        return qs

def generate_list(request,pk):
    query = request.GET.getlist('query',None)
    print(query)
    if query:
        query2 = reduce(operator.and_, (Q(arr__icontains = item) for item in query))
        user_list = Arrpart.objects.filter(query2,nft_template__pk=pk)
    else:
        user_list = Arrpart.objects.filter(nft_template__pk=pk)
    page = request.GET.get('page', 1)
    paginator = Paginator(user_list, 50)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    uscount = user_list.count()
    return render(request,"avatar_generator/get.html", { 'object_list': users,"count":uscount })

class collectableCreateView(CreateView):
    model = NftTemplate
    template_name = "avatar_generator/form.html"
    form_class = forms.NftTemplateFrom
    
def createNft(request):
    if request.method == "POST":
        form = forms.NftTemplateFrom(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save()
            return JsonResponse({"data":obj.id},status=200)
        else:
            print(form.errors)
            return JsonResponse({"data":str(form.errors)},status=200)
    else:
        return render(request, "avatar_generator/form.html", {"form":forms.NftTemplateFrom})
    
class collectableDetail(CreateView):
    model = Sections
    template_name = "avatar_generator/upload_sections.html"
    form_class = forms.SectionsFrom

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        context["object"] = NftTemplate.objects.get(id=pk)
        context["object_list"] = Sections.objects.filter(nft_template__id=pk)
        return context
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        pk = self.kwargs.get("pk")
        obj.nft_template =  NftTemplate.objects.get(id=pk)
        obj.save()
        return super().form_valid(form)


def update_settings(request,pk):
    obj = get_object_or_404(NftTemplate, pk=pk)
    form = forms.NftTemplateFrom(
        request.POST or None, request.FILES or None, instance=obj
    )
    if request.method == "POST":
        if form.is_valid():
            obj = form.save()
            msg = pgettext_lazy("Dashboard message", "Settings has been update  %s") % (
                obj.title,
            )
            messages.success(request, msg)
            return redirect( reverse("collectibles:collectables_detail", kwargs={"pk": pk}))
        else:
            msg = pgettext_lazy("Dashboard message", " %s") % (
                form.errors,
            )
            messages.success(request, msg)
            return redirect( reverse("collectibles:collectables_detail", kwargs={"pk":pk}))
    ctx = {"form": form, "form_url": reverse("collectibles:update_settings", kwargs={"pk":pk})}
    return TemplateResponse(request, "avatar_generator/form_modal.html", ctx)

def delete_section(request,pk):
    obj = get_object_or_404(Sections, pk=pk)
    nft_pk = obj.nft_template.pk
    if request.method == "POST":
        obj.delete()
        return redirect( reverse("collectibles:collectables_detail", kwargs={"pk":nft_pk}))
    ctx = {"form_url": reverse("collectibles:delete_section", kwargs={"pk":pk}), "object":obj}
    return TemplateResponse(request, "avatar_generator/delete_section.html", ctx)

def upload_image(request,pk):
    section = get_object_or_404(Sections, pk=pk)
    form = forms.ImageFrom(
        request.POST or None, request.FILES or None
    )
    if request.method == "POST":
        if form.is_valid():
            obj = form.save(commit=False)
            obj.section = section
            obj.position_x = section.position_x
            obj.position_y = section.position_y
            obj.sort_order = section.sort_order
            obj.save()
            msg = pgettext_lazy("Dashboard message", "Image Has Benn Uploaded ")
            messages.success(request, msg)
            return JsonResponse({"data":reverse("collectibles:collectables_detail", kwargs={"pk":section.nft_template.pk})},status=200)
        else:
            msg = pgettext_lazy("Dashboard message", " %s") % (
                form.errors,
            )
            messages.success(request, msg)
            return redirect( reverse("collectibles:collectables_detail", kwargs={"pk":pk}))
    ctx = {"form": form, "form_url": reverse("collectibles:upload_image", kwargs={"pk":pk}), "object":section}
    return TemplateResponse(request, "avatar_generator/images/detail_list.html", ctx)

def generate_nft(request, pk):
    nft = get_object_or_404(NftTemplate, pk=pk)
    sections = Sections.objects.filter(nft_template_id=pk)
    arr = []
    for section in sections:
        image_list = list(section.images_set.all().annotate(exluded=ArrayAgg('exclude')).values("id","image","position_x","position_y","exluded").distinct())
        serialized_q = json.dumps(list(image_list), cls=DjangoJSONEncoder)
        arr.append(serialized_q)
    return TemplateResponse(request, "avatar_generator/generate.html", {"sections":arr,"pk":pk,})

def delete_image(request,pk):
    image = get_object_or_404(Images,pk=pk)
    section = image.section.id
    if request.method == "POST":
        image.delete()
        msg = pgettext_lazy("Dashboard message", "Image Has Benn Deleted ")
        messages.success(request, msg)
        return redirect( reverse("collectibles:upload_image", kwargs={"pk":section}))
    ctx = { "form_url": reverse("collectibles:delete_image", kwargs={"pk":pk}), "object":image}
    return TemplateResponse(request, "avatar_generator/images/delete_image.html", ctx)


def update_image(request,pk):
    image = get_object_or_404(Images,pk=pk)
    section = image.section
    sections_selected = Sections.objects.filter(nft_template=section.nft_template).exclude(id=section.id).values_list("id", flat=True)
    images = Images.objects.filter(section_id__in=list(sections_selected))
    form = forms.ImageFromUpdate(data=request.POST or None,files=request.FILES or None,images_qs=images, instance=image)
    print(form.errors)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            msg = pgettext_lazy("Dashboard message", "Image Has Benn updated ")
            messages.success(request, msg)
        else:
            msg = pgettext_lazy("Dashboard message", str(form.errors))
            messages.success(request, msg)
        return redirect( reverse("collectibles:upload_image", kwargs={"pk":image.section.id}))
    ctx = { "form_url": reverse("collectibles:update_image", kwargs={"pk":pk}), "form": form,"object":image}
    return TemplateResponse(request, "avatar_generator/images/update_images.html", ctx)

def reset_image(request,pk):
    section = get_object_or_404(Sections, pk=pk)
    imgs = Images.objects.filter(section_id=pk)
    print(imgs)
    for img in imgs:
        img.exclude.clear()
        img.save()
    return redirect( reverse("collectibles:upload_image", kwargs={"pk":pk}))

@require_POST
def ajax_upload_image(request, obj_pk):
    section = get_object_or_404(Sections, pk=obj_pk)
    form = forms.ImageFrom(
        request.POST or None, request.FILES or None, section=section
    )
    ctx = {}
    status = 200
    if form.is_valid():
        image = form.save()
        ctx = {"id": image.pk, "image": None, "order": image.sort_order}
    elif form.errors:
        status = 400
        ctx = {"error": form.errors}
    return JsonResponse(ctx, status=status)


def product_image_delete(request, obj_pk, img_pk):
    section = get_object_or_404(Sections, pk=obj_pk)
    image = get_object_or_404(Images, pk=img_pk)
    if request.method == "POST":
        image.delete()
        msg = pgettext_lazy("Dashboard message", "Removed image %s") % (

nft_cryptopunks_generator/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

nft_cryptopunks_generator/templates/avatar_generator/images/delete_image.html
{% extends "modal_base.html" %}
{% load widget_tweaks %}
{% block action_url %}
{{ form_url }}
{% endblock %}
 
 {% block title %}
   Are you sure you want to delete this image
 {% endblock title %}
   
{% block content %}
<div class="form-group text-center">
    <img class="m-auto w-100" src="{{ object.image.url }}" alt="">
</div>
{% endblock %}
{% block script %}

{% endblock %}

nft_cryptopunks_generator/templates/avatar_generator/images/detail_list.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block stylesheet %}
<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
<style>
  ul#id_exclude li {
    display: inline-block;
    width: 49%;
}

ul#id_exclude {
    display: block;
    width: 100%;
    height: 100%;
}
</style>
{% endblock stylesheet %}
  
  {% block menu %}
  <a href="{% url "collectibles:reset_image" pk=object.pk %}">reset many to many</a>

  {% endblock menu %}
    
{% block content %}
    <center><h3>Upload Images for {{ object.name }}</h3></center>
  <div class="row text-center">
        <div class="col-md-12 mb-3">
        <form id="upload-form" action="{{form_url}}" class="dropzone">
          <!-- this is were the previews should be shown. -->
          {% csrf_token %}
          <div class="row">
            <div class="col-3">
              <div class="row border">
                <div class="form-group col">
                  <label for="exampleInputEmail1">{{ form.height.label }}</label>
                  {% render_field form.height class="form-control" %}
                </div>
                <div class="form-group col">
                  <label for="exampleInputEmail1">{{ form.width.label }}</label>
                  {% render_field form.width class="form-control" %}
                </div>
              </div>
              <button type="submit" class="btn btn-primary w-100">Upload</button>
            </div>
            <div class="col-md-6">
              <div class="previews"></div>
              <div class="dz-message" data-dz-message> <img width="25" src="{% static "images/icons/folder.png" %}" alt=""><span>Upload your Image here</span></div>

            </div>
          </div>
        </form>
        
        <div class="row mt-3"> 
          {% for object in object.images_set.all %}
            <div class="col-md-3 mb-2">
              <div class="card">
                <img class="card-img-top" src="{{ object.image.url }}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">Position: {{ object.sort_order }}</p>
                  <div class="row ">
                    <button href="{% url "collectibles:update_image" pk=object.pk %}" data-toggle="modal"  data-bs-toggle="modal" data-bs-target="#exampleModal" class="modal-trigger-custom btn btn-primary modal-trigger-custom"  class="btn btn-danger  m-auto mb-2">Update Position</button>
                    <button href="{% url "collectibles:delete_image" pk=object.pk %}" data-toggle="modal"  data-bs-toggle="modal" data-bs-target="#exampleModal" class="modal-trigger-custom btn btn-danger modal-trigger-custom"  class="btn btn-danger  m-auto mb-2">Delete Image</button>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}
        </div>
          
    </div>

  </div>

  {% include "modal.html" with id_modal="exampleModal" %}
  
{% endblock %}

{% block inline_javascript %}
<script>
  $("body").on("click","#toggle-check",function(){
    $(':checkbox[name=exclude]').prop('checked', this.checked);
  })  
  Dropzone.options.uploadForm = { // The camelized version of the ID of the form element
  // The configuration we've talked about above
  paramName:"image",
  autoProcessQueue: false,
  uploadMultiple: false,
  parallelUploads: 1000,
  previewsContainer: ".previews",
  // The setting up of the dropzone
  success: function(file, response){

    },
  init: function() {
    var myDropzone = this;
    // First change the button to actually tell Dropzone to process the queue.
    this.on("maxfilesexceeded", function(file) {
            this.removeAllFiles();
            this.addFile(file);
      });
    this.element.querySelector("button[type=submit]").addEventListener("click", function(e) {
      // Make sure that the form isn't actually being sent.
      e.preventDefault();
        e.stopPropagation();
        myDropzone.processQueue();
      
    });
    
    // Listen to the sendingmultiple event. In this case, it's the sendingmultiple event instead
    // of the sending event because uploadMultiple is set to true.
    this.on("sendingmultiple", function() {
      // Gets triggered when the form is actually being sent.
      // Hide the success button or the complete form.
    });
    this.on("successmultiple", function(files, response) {
      // Gets triggered when the files have successfully been sent.
      // Redirect user or notify of success.
    });
    this.on("errormultiple", function(files, response) {
      // Gets triggered when there was an error sending the files.
      // Maybe show form again, and notify user of error
    });
    
  }
 
}
   $(document).ready(function(){
    
 

   })
  </script>
{% endblock inline_javascript %}
  

nft_cryptopunks_generator/templates/avatar_generator/images/update_images.html
{% extends "modal_base.html" %}
{% load widget_tweaks %}
{% block action_url %}
{{ form_url }}
{% endblock %}
 
 {% block title %}
   Update Image {{ object.image.name }}{{ object.sort_order }}
 {% endblock title %}
   
{% block content %}
<div class="form-group text-center">
  <img class="m-auto w-100" src="{{ object.image.url }}" alt="">
</div>
<div class="form-group">
  <label for="nom" class="">Position</label>
      {% render_field form.sort_order   class="form-control"%}
</div>
  <div class="form-group">
    <label for="nom" class="col-sm-12  col-form-label-sm">Width</label>
        {% render_field form.width   class="form-control"%}
</div>
<div class="form-group">
  <label for="nom" class="col-sm-12  col-form-label-sm">Height</label>
      {% render_field form.height   class="form-control"%}
</div>
<div class="form-group">
  <label for="nom" class="col-sm-12  col-form-label-sm">Exclude</label>
  <label for="">toggle check
    <input type="checkbox" id="toggle-check">
  </label>
      {% render_field form.exclude   class="form-control"%}
</div>
{% endblock %}
{% block script %}

{% endblock %}