config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("nft_cryptopunks_generator.users.urls", namespace="users")),
    path("", include("nft_cryptopunks_generator.avatar.urls", namespace="collectibles")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

nft_cryptopunks_generator/avatar/urls.py
from django.urls import include, path
from .views import TemplateList, collectableDetail, createNft, delete_image, update_settings, savearr, delete_section, upload_image, Generatelist, generate_list, generate_nft, update_image, reset_image, delete_image, delete_partarr
app_name = "collectibles"
urlpatterns = [
    path("", TemplateList.as_view(), name="home"),
    path("create/", createNft, name="collectables_create"),
    path("<int:pk>/", collectableDetail.as_view(), name="collectables_detail"),
    path("section/<int:pk>/", update_settings, name="update_settings"),
    path("section/delete/<int:pk>/", delete_section, name="delete_section"),
    path("section/image/<int:pk>/", upload_image, name="upload_image"),
    path("generate/<int:pk>/", generate_nft, name="generate_nft"),
    path("delete/imge/<int:pk>/", delete_image, name="delete_image"),
    path("update/imge/<int:pk>/", update_image, name="update_image"),
    path("reset/imge/<int:pk>/", reset_image, name="reset_image"),
    path("<int:id>/section/", TemplateList.as_view(), name="template_list"),
    path("<int:pk>/save_arr/", savearr, name="save_arr"),
    path("<int:pk>/generate_part/", generate_list, name="generate_part"),
    path("delete/<int:pk>/", delete_partarr, name="delete_partarr"),
]

nft_cryptopunks_generator/users/urls.py
from django.urls import path

from nft_cryptopunks_generator.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

nft_cryptopunks_generator/avatar/forms.py
from django import forms
from django.db.models import fields
from .models import Arrpart, NftTemplate, Sections, Images
from .thumbnails import create_product_thumbnails
from django.utils.safestring import mark_safe

class NftTemplateFrom(forms.ModelForm):
    class Meta:
        model = NftTemplate
        fields = ("title", "width","height","file")
    def __init__(self, *args, **kwargs):
        super(NftTemplateFrom, self).__init__(*args, **kwargs)
        self.fields['title'].required = True
        self.fields['width'].required = True
        self.fields['height'].required = True
        self.fields['file'].required = True


class SectionsFrom(forms.ModelForm):
    class Meta:
        model = Sections
        exclude = ("nft_template",)


class ImageFrom(forms.ModelForm):
    class Meta:
        model = Images
        exclude = ("section","raretiy","exclude")

    def save(self, commit=True):
        image = super().save(commit=commit)
        return image

class CustomChoiceField(forms.ModelMultipleChoiceField):

    def label_from_instance(self, obj):
        return mark_safe("<img class='w-75' src='{}'/> <span>{}</span>".format(obj.image.url,obj.image.name))
        
class ImageFromUpdate(forms.ModelForm):
    class Meta:
        model = Images
        fields = ("sort_order","width","height","exclude")

    def __init__(self,images_qs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Make the query here
        print(images_qs)
        self.fields['exclude'] = CustomChoiceField(widget=forms.CheckboxSelectMultiple, queryset=images_qs,required=False,)

class ArrForm(forms.ModelForm):
    class Meta:
        model = Arrpart
        fields = ("arr",)

class OrderedModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def clean(self, value):
        qs = super().clean(value)
        keys = list(map(int, value))
        return sorted(qs, key=lambda v: keys.index(v.pk))


class ReorderProductImagesForm(forms.ModelForm):
    ordered_images = OrderedModelMultipleChoiceField(
        queryset=Images.objects.none()
    )

    class Meta:
        model = Sections
        fields = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            self.fields["ordered_images"].queryset = self.instance.images.all()

    def save(self):
        for order, image in enumerate(self.cleaned_data["ordered_images"]):
            image.sort_order = order
            image.save()
        return self.instance

nft_cryptopunks_generator/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

nft_cryptopunks_generator/avatar/views.py
import re
from django.contrib import messages
from django.db.models import fields
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.postgres.aggregates import ArrayAgg
import operator
from django.db.models import Q
from functools import reduce
import base64
from django.core.files.base import ContentFile

# Create your views here.
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, ListView, CreateView,UpdateView
from django.views.generic.detail import DetailView
from django.views.decorators.csrf import csrf_exempt
import json
from django.core.serializers.json import DjangoJSONEncoder
from .models import NftTemplate, Sections, Images, Arrpart
from . import forms
from django.urls import reverse
from rest_framework import serializers
from . import models
from django.core import serializers as myser
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class ImageSerializer(serializers.ModelSerializer):
    class Meta:
        model = Images
        fields = ("exclude","image","sort_order","position_x","position_y")


class TemplateList(ListView):
    template_name = "avatar_generator/index.html"
    model = NftTemplate
    paginate_by = 100
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

@csrf_exempt
def savearr(request,pk):
    nft_template = get_object_or_404(NftTemplate,pk=pk)
    post_data =  request.POST
    print(post_data.get("data"))
    print("######################")
    if post_data:
        Arrpart.objects.create(arr=post_data.get("data"), nft_template=nft_template)
    return JsonResponse({"data": "uploaded"},status=200)

class Generatelist(ListView):
    model = Arrpart
    template_name = "avatar_generator/get.html"
    paginate_by = 1

    def get_queryset(self):
        print(self.kwargs.get("kwargs",None))
        qs = super().get_queryset()
        return qs

def generate_list(request,pk):
    query = request.GET.getlist('query',None)
    print(query)
    if query:
        query2 = reduce(operator.and_, (Q(arr__icontains = item) for item in query))
        user_list = Arrpart.objects.filter(query2,nft_template__pk=pk)
    else:
        user_list = Arrpart.objects.filter(nft_template__pk=pk)
    page = request.GET.get('page', 1)
    paginator = Paginator(user_list, 50)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    uscount = user_list.count()
    return render(request,"avatar_generator/get.html", { 'object_list': users,"count":uscount })

class collectableCreateView(CreateView):
    model = NftTemplate
    template_name = "avatar_generator/form.html"
    form_class = forms.NftTemplateFrom
    
def createNft(request):
    if request.method == "POST":
        form = forms.NftTemplateFrom(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save()
            return JsonResponse({"data":obj.id},status=200)
        else:
            print(form.errors)
            return JsonResponse({"data":str(form.errors)},status=200)
    else:
        return render(request, "avatar_generator/form.html", {"form":forms.NftTemplateFrom})
    
class collectableDetail(CreateView):
    model = Sections
    template_name = "avatar_generator/upload_sections.html"
    form_class = forms.SectionsFrom

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        context["object"] = NftTemplate.objects.get(id=pk)
        context["object_list"] = Sections.objects.filter(nft_template__id=pk)
        return context
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        pk = self.kwargs.get("pk")
        obj.nft_template =  NftTemplate.objects.get(id=pk)
        obj.save()
        return super().form_valid(form)


def update_settings(request,pk):
    obj = get_object_or_404(NftTemplate, pk=pk)
    form = forms.NftTemplateFrom(
        request.POST or None, request.FILES or None, instance=obj
    )
    if request.method == "POST":
        if form.is_valid():
            obj = form.save()
            msg = pgettext_lazy("Dashboard message", "Settings has been update  %s") % (
                obj.title,
            )
            messages.success(request, msg)
            return redirect( reverse("collectibles:collectables_detail", kwargs={"pk": pk}))
        else:
            msg = pgettext_lazy("Dashboard message", " %s") % (
                form.errors,
            )
            messages.success(request, msg)
            return redirect( reverse("collectibles:collectables_detail", kwargs={"pk":pk}))
    ctx = {"form": form, "form_url": reverse("collectibles:update_settings", kwargs={"pk":pk})}
    return TemplateResponse(request, "avatar_generator/form_modal.html", ctx)

def delete_section(request,pk):
    obj = get_object_or_404(Sections, pk=pk)
    nft_pk = obj.nft_template.pk
    if request.method == "POST":
        obj.delete()
        return redirect( reverse("collectibles:collectables_detail", kwargs={"pk":nft_pk}))
    ctx = {"form_url": reverse("collectibles:delete_section", kwargs={"pk":pk}), "object":obj}
    return TemplateResponse(request, "avatar_generator/delete_section.html", ctx)

def upload_image(request,pk):
    section = get_object_or_404(Sections, pk=pk)
    form = forms.ImageFrom(
        request.POST or None, request.FILES or None
    )
    if request.method == "POST":
        if form.is_valid():
            obj = form.save(commit=False)
            obj.section = section
            obj.position_x = section.position_x
            obj.position_y = section.position_y
            obj.sort_order = section.sort_order
            obj.save()
            msg = pgettext_lazy("Dashboard message", "Image Has Benn Uploaded ")
            messages.success(request, msg)
            return JsonResponse({"data":reverse("collectibles:collectables_detail", kwargs={"pk":section.nft_template.pk})},status=200)
        else:
            msg = pgettext_lazy("Dashboard message", " %s") % (
                form.errors,
            )
            messages.success(request, msg)
            return redirect( reverse("collectibles:collectables_detail", kwargs={"pk":pk}))
    ctx = {"form": form, "form_url": reverse("collectibles:upload_image", kwargs={"pk":pk}), "object":section}
    return TemplateResponse(request, "avatar_generator/images/detail_list.html", ctx)

def generate_nft(request, pk):
    nft = get_object_or_404(NftTemplate, pk=pk)
    sections = Sections.objects.filter(nft_template_id=pk)
    arr = []
    for section in sections:
        image_list = list(section.images_set.all().annotate(exluded=ArrayAgg('exclude')).values("id","image","position_x","position_y","exluded").distinct())
        serialized_q = json.dumps(list(image_list), cls=DjangoJSONEncoder)
        arr.append(serialized_q)
    return TemplateResponse(request, "avatar_generator/generate.html", {"sections":arr,"pk":pk,})

def delete_image(request,pk):
    image = get_object_or_404(Images,pk=pk)
    section = image.section.id
    if request.method == "POST":
        image.delete()
        msg = pgettext_lazy("Dashboard message", "Image Has Benn Deleted ")
        messages.success(request, msg)
        return redirect( reverse("collectibles:upload_image", kwargs={"pk":section}))
    ctx = { "form_url": reverse("collectibles:delete_image", kwargs={"pk":pk}), "object":image}
    return TemplateResponse(request, "avatar_generator/images/delete_image.html", ctx)


def update_image(request,pk):
    image = get_object_or_404(Images,pk=pk)
    section = image.section
    sections_selected = Sections.objects.filter(nft_template=section.nft_template).exclude(id=section.id).values_list("id", flat=True)
    images = Images.objects.filter(section_id__in=list(sections_selected))
    form = forms.ImageFromUpdate(data=request.POST or None,files=request.FILES or None,images_qs=images, instance=image)
    print(form.errors)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            msg = pgettext_lazy("Dashboard message", "Image Has Benn updated ")
            messages.success(request, msg)
        else:
            msg = pgettext_lazy("Dashboard message", str(form.errors))
            messages.success(request, msg)
        return redirect( reverse("collectibles:upload_image", kwargs={"pk":image.section.id}))
    ctx = { "form_url": reverse("collectibles:update_image", kwargs={"pk":pk}), "form": form,"object":image}
    return TemplateResponse(request, "avatar_generator/images/update_images.html", ctx)

def reset_image(request,pk):
    section = get_object_or_404(Sections, pk=pk)
    imgs = Images.objects.filter(section_id=pk)
    print(imgs)
    for img in imgs:
        img.exclude.clear()
        img.save()
    return redirect( reverse("collectibles:upload_image", kwargs={"pk":pk}))

@require_POST
def ajax_upload_image(request, obj_pk):
    section = get_object_or_404(Sections, pk=obj_pk)
    form = forms.ImageFrom(
        request.POST or None, request.FILES or None, section=section
    )
    ctx = {}
    status = 200
    if form.is_valid():
        image = form.save()
        ctx = {"id": image.pk, "image": None, "order": image.sort_order}
    elif form.errors:
        status = 400
        ctx = {"error": form.errors}
    return JsonResponse(ctx, status=status)


def product_image_delete(request, obj_pk, img_pk):
    section = get_object_or_404(Sections, pk=obj_pk)
    image = get_object_or_404(Images, pk=img_pk)
    if request.method == "POST":
        image.delete()
        msg = pgettext_lazy("Dashboard message", "Removed image %s") % (

nft_cryptopunks_generator/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

nft_cryptopunks_generator/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}nft cryptopunks generator{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="nft cryptopunks generator">
    <meta name="author" content="brahim chougrani">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    
    {% block stylesheet %}
      
    {% endblock stylesheet %}
      
  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'collectibles:home' %}">nft cryptopunks generator</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'collectibles:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url "collectibles:collectables_create"  %}">Create nft Template </a>
            </li>
            {% block menu %}
              
            {% endblock menu %}
              
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}
        {% block javascript %}
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>
      <script defer src="{% static 'js/project_2.js' %}"></script>
    {% endblock javascript %}
    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>

nft_cryptopunks_generator/templates/modal.html
<div class="modal fade" id="{{ id_modal }}" tabindex="-1" role="dialog" aria-labelledby="{{ id_modal }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!--end modal-footer-->
        </div><!--end modal-content-->
    </div><!--end modal-dialog-->
</div>

nft_cryptopunks_generator/templates/modal_base.html
{% load i18n %}
          <div class="modal-header">
              <h6 class="modal-title m-0" id="exampleModalDefaultLabel">{% block title %}{% endblock %}</h6>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div><!--end modal-header-->
          <div class="modal-body">
              <div class="">
                {% block form_container %}
                <form
                    role="form" method="post" action="{% block action_url %}#!{% endblock %}"
                    class="{% block form_class %}form-async{% endblock %}" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <div class="col 12">
                          {% for error in form.non_field_errors %}
                            <p class="help-block materialize-red-text">{{ error }}</p>
                          {% endfor %}
                        </div>
                      {% endif %}
                    {% block content %}{% endblock %}
                    {% block bottom %}
                        <div class="modal-footer">
                          <span class="left">
                          {% block actions_left %}{% endblock %}
                        </span>
                         <button  type="button" class="btn btn-secondary" data-dismiss="modal">
                           <i class="flaticon-cancel-12"></i>
                           {% block cancel_action %} {% trans "Annuler" context "Dashboard cancel action" %} {% endblock %}
                         </button>
                         <button type="submit" class="btn btn-soft-primary btn-sm">
                          {% block primary_action %}Sauvgarder{% endblock %}
                        </button>
                      </div>
                    {% endblock %}
                  </form>
              {% endblock %}
              {% block free_content_modal %}
            
              {% endblock %}
              </div><!--end row-->                                                      
          </div><!--end modal-body-->
          

{% block script %}

{% endblock %}